version: '3'
services:
  mongo:
    container_name: mongo-triangle
    image: "gcr.io/steel-math-257901/mongo-triangle"
    command: mongod --port 27018
    ports:
      - "27018:27018"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1q2w3e
    networks:
      - triangle_network
  app:  
    container_name: triangle-test
    restart: "always"
    image: "gcr.io/steel-math-257901/triangle-test"
    ports:
      - "5555:5555"
    environment:
      - API_PORT=5555
      - MONGO_HOST=mongo-triangle
      - MONGO_PORT=27018
      - MONGO_DB=triangle
      - MONGO_USER=root
      - MONGO_PASSWORD=1q2w3e
    networks:
      - triangle_network
networks:
  triangle_network: