module.exports = [
  {
    row: 2,
    leftChild: { index: 0, value: 9 },
    rightChild: { index: 1, value: 7 },
    node: { index: 0, value: 9 },
    bigger: 'right',
    sum: 15,
  },
  {
    row: 2,
    leftChild: { index: 1, value: 6 },
    rightChild: { index: 2, value: 8 },
    node: { index: 1, value: 7 },
    bigger: 'right',
    sum: 15,
  },
  {
    row: 2,
    leftChild: { index: 2, value: 8 },
    rightChild: { index: 3, value: 4 },
    node: { index: 2, value: 4 },
    bigger: 'left',
    sum: 9,
  },
  {
    row: 1,
    leftChild: { index: 0, value: 15 },
    rightChild: { index: 1, value: 15 },
    node: { index: 0, value: 3 },
    bigger: 'left',
    sum: 18,
  },
  {
    row: 1,
    leftChild: { index: 1, value: 15 },
    rightChild: { index: 2, value: 9 },
    node: { index: 1, value: 5 },
    bigger: 'left',
    sum: 20,
  },
  {
    row: 0,
    leftChild: { index: 0, value: 18 },
    rightChild: { index: 1, value: 20 },
    node: { index: 0, value: 6 },
    bigger: 'right',
    sum: 26,
  },
];
